version = 1
SPDX-PackageName = "btp-intelligent-situation-automation"
SPDX-PackageSupplier = "Sanghamitra Bhattacharya (sanghamitra.bhattacharya@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/btp-intelligent-situation-automation"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and btp-intelligent-situation-automation contributors"
SPDX-License-Identifier = "CC-BY-4.0"
